name: docker hub login
on: workflow_dispatch
jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin
      - name: pull existing image
        run: docker pull nginx:latest
      - name: rename the image
        run: docker image tag nginx:latest ${{ vars.DB_USERNAME }}/nginx:latest
      - name: list images
        run: ls
      - name: push image to dockerhub
        run: docker push ${{ vars.DB_USERNAME }}/nginx:latest   
