name: multiple jobs
on: workflow_dispatch
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4.2.2
      - name: list the code cloned
        run: 
          ls -a .github/workflows
  build:
    needs: checkout  
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with: 
          node-version: 20
      - name: check node installation
        run: node -v 
      - name: build application
        run: echo "build is completed"
  test-job:
    needs: checkout
    runs-on: ubuntu-latest
    steps: 
      - name: testing
        run: echo "Testing is done"

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Setup NGINX service for Linux/macOS/Windows
        uses: nyurik/action-setup-nginx@v1.1
        with:
          port: 80
      - name: deploy application
        run: echo "deployment is done"
      
     
