name: secrets and variables
on: workflow_dispatch
jobs:
  secrets:
    env:
      USERNAME: Admin
    runs-on: ubuntu-latest
    steps:
      - name: login database
        run: echo "login database using password 'Admin123' and username $USERNAME"
  
