name: secrets and variables
on: workflow_dispatch
jobs:
  secrets:
    env:
      USERNAME: Admin
      PASSWORD: Admin123
    runs-on: ubuntu-latest
    steps:
      - name: login database
        run: echo "login database using password $PASSWORD and username $USERNAME"
      - name: display database credentials
        run: echo "db password $PASSWORD and username $USERNAME"
  
