name: secrets and variables
on: workflow_dispatch
jobs:
  secrets:
    env:
      USERNAME: Admin
      PASSWORD: Admin123
    runs-on: ubuntu-latest
    steps:
      - name: login database
        run: echo "login database using password ${{ secrets.DB_PASSWORD }} and username ${{ vars.DB_USERNAME }}"
      - name: display database credentials
        run: echo "db password ${{ secrets.DB_PASSWORD }} and username ${{ vars.DB_USERNAME }}"
      - name: pull existing image
        run: docker pull nginx:latest
      - name: rename the image
        run: docker image tag nginx:latest ${{ vars.DB_USERNAME }}/nginx:latest
      - name: list images
        run: ls
      - name: push image to dockerhub
        run: docker push ${{ vars.DB_USERNAME }}/nginx:latest 
  
