name: selfhost runner
on: workflow_dispatch
jobs:
  build:
    runs-on: build
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: list the files and folders
        run:
          ls -a
          pwd
