name: selfhost runner
on: workflow_dispatch
jobs:
  build:
    runs-on: build
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: to know the dir
        run: pwd
          
          
