name: selfhost runner
on: workflow_dispatch
jobs:
  build:
    runs-on: build
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: list files and folders
        run: ls
      - name: install nginx
        run: sudo apt install nginx -y
          
          
